### ISSUE TITLE
Vet Action Fails with package-lock.json Files Larger than 1 MB

### ISSUE THREAD

**Issue by shubham-chaskar** [safedep/vet-action#37]
The vet-action GitHub Action is failing when processing package-lock.json files larger than 1 MB. This issue seems to occur consistently with larger files, leading to failed scans.

**Steps to Reproduce:**

1. Create a repository with a package-lock.json file larger than 1 MB.
2. Configure the vet-action to run on this repository.
3. Create a pull request to trigger the GitHub Action.

![Screenshot 2024-08-07 at 5 56 13 PM](https://github.com/user-attachments/assets/2e97fabf-39be-4798-ab00-81863ffce6f0)

I noticed that checking out of package-lock.json is not properly working. Vet creates a new file for this which is empty.

![Screenshot 2024-08-07 at 6 01 47 PM](https://github.com/user-attachments/assets/84f12cce-8069-410e-be80-117007441a8b)

Verified that the package-lock.json file is valid JSON and not corrupted. I haven't tried to reproduce this issue for other supported lockfiles.

**Comment by abhisek** [comment]
Thanks for reporting this issue @shubham-chaskar I have pushed a fix in https://github.com/safedep/vet-action/pull/38

I am working on testing this with >1MB `package-lock.json`. In the mean time, do you want to try out the fix branch and see if the patch works for you? You just need to change `uses: safedep/vet-action@v1` tag for the action to `uses: safedep/vet-action@37-fix-octokit-content-size-limit` which is the name of the branch containing the fix.

Let me know if you are able to test and if it works for you.

**Comment by shubham-chaskar** [comment]
Hello @abhisek, The fix is working. but faced another issue related to the comment. This is more of an issue at the GitHub end.

I introduced a lot of new packages in a single PR which might be unrealistic in the real world. This is not a blocker for us right now. Just a suggestion that we can combine "Lockfile Poisoning Detected" to reduce comment size.


![Screenshot 2024-08-08 at 11 18 03 AM](https://github.com/user-attachments/assets/7700bb82-ba6e-44ed-adb1-14b2b7a70d22)

Thank you for the prompt response.

**Comment by shubham-chaskar** [comment]
This image is from another successful vet execution. As I mentioned earlier if we can combine results based on an "untrusted host" it might solve this issue.

![Screenshot 2024-08-08 at 11 27 00 AM](https://github.com/user-attachments/assets/7a4f7709-0b07-4fab-b367-5270038ea385)

**Comment by abhisek** [comment]
@shubham-chaskar I am adding an action input called `trusted-registries`. You should be able to add your private registry URL as trusted to avoid this problem. Have a look:

https://github.com/safedep/vet-action/tree/37-fix-octokit-content-size-limit?tab=readme-ov-file#configuration

Do note: It's yet to be release. I will release this later today.

**Comment by abhisek** [comment]
@shubham-chaskar I have released the fixes to `v1` tag of the action. I am going to close this issue now but feel free to re-open this issue or create a new issue in case it does not work for you or you encounter any other problem.

Thanks for your reporting and help improving `vet`.
